### PR TITLE
BMPlayerConfig

### PR DESCRIPTION
**Pull request by Mik-chan**
Now it matters which values BMPlayerConfig stores

### CODE REVIEW

**Comment by RahulSriram** [comment]
This PR is really good! @BrikerMan please merge it into the pod soon!

**Comment by BrikerMan** [comment]
sorry for the delay~

**Comment by talk2cerlin** [comment]
@BrikerMan When can we expect this to be released in pod?

**Comment by RahulSriram** [comment]
@talk2cerlin, just use 
`pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git'`
if you need the latest changes

**Comment by talk2cerlin** [comment]
@RahulSriram (AFAIK) this will fetch the latest commit and do the installation which will lead to crashes if someone commits some incomplete code to master.

i can do `pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git', :commit => '0524fadd7c70b4a6ef0f47e72ddfbf38e59a8d79'` but this will stop me from fetching the latest release.

i think for now i will install from commit.

**Comment by BrikerMan** [comment]
Will release next week. I am really busy this week.

**Pull request merged**
