### PR TITLE
Add PlayerStateChanged callback

### PR DESCRIPTION
**Pull request by benbahrenburg**
Thank you for creating a great player.  For a project I need the calling layer or controller to be able to listen to specific player state changed events.  Similarly to the player is playing event I've created a PR which calls a closure, i.e. callback style.

~~~
        player?.playerStateDidChange = {(state: BMPlayerState) in
            print("player state changed to: \(state)")
        }
~~~

Thank you for all of your help and building a great player.

### CODE REVIEW

**Comment by BrikerMan** [comment]
I have already added the `BMPlayerDelegate`. Maybe it will suit for your request. Tell me if it can't.

**Comment by benbahrenburg** [comment]
@BrikerMan, I agree it would be nice to be able to subclass so the calling app could consume state changes, then call super to forward the change event back to the master class.  Do you have an example of how this can be implemented? I might be incorrect, but this seems to require major refactors to the player. 

Because of these changes I thought it was best to add callback style closures.

**Comment by BrikerMan** [comment]
Check the new Readme I just updated. But it is cool to have both the block
and delegate call back to get the status. Will add this to demo tomorrow.
It is bed time now for me now.

Ben Bahrenburg <notifications@github.com>于2016年12月1日 周四下午10:45写道：

**Comment by benbahrenburg** [comment]
Thanks @BrikerMan . Would be great to see an example.  Thank you for all of your help and hard work.

**Comment by BrikerMan** [comment]
Updated readme and the Example project~

**Pull request closed without merging**
